### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by thijstriemstra**
Fixes:
- typo in readme related to django session middleware
- add missing trans tag in template
- use blocktrans tag in template

### CODE REVIEW

**Comment by nigma** [comment]
Thanks!

**Comment by thijstriemstra** [comment]
Thanks for merging. Could you make a new release as well, I'd like to use the admin view in 0.2 instead of duplicating it.

**Comment by nigma** [comment]
Sure. Would you also like to include NL or other translation in the release?

**Comment by thijstriemstra** [comment]
Sure, opened a new pull request for that.

**Pull request merged**
